# This action is meant to be triggered manually via the GitHub UI
name: Create Release Tag
on:
  workflow_dispatch: {}

jobs:
  release:
    name: Run cargo-release
    runs-on: ubuntu-latest
    steps:
    # We can't use the provided `GITHUB_TOKEN` here because it doesn't trigger
    # other workflows (like Docker Release). See docs for details:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
    #
    # Generate a token (with "repo" permissions), and add it to the repo settings:
    # https://github.com/settings/tokens/new?scopes=repo
    # https://github.com/your-username/your-repo/settings/secrets/actions
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.54.0
        override: true
    - uses: Swatinem/rust-cache@v1.2.0
    - name: Set git user
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Run cargo-release
      run: |
        cd /tmp
        curl -L https://github.com/crate-ci/cargo-release/releases/download/v0.17.1/cargo-release-v0.17.1-x86_64-unknown-linux-gnu.tar.gz | tar xvz --strip-components=1
        cd -
        /tmp/cargo-release release --no-confirm --execute --no-verify

